config/routes.rb
Rails.application.routes.draw do

  resources :pages

  resources :services

    get 'api/business_centers'
    get 'api/cities'
    get 'api/regions'
    get 'api/metros'
    get 'api/room_types'
    get 'api/services'
    get 'api/business_center/:id' => 'api#business_center'
    get 'api/business_centers_for_map'
    get 'api/similar_business_centers/:id' => 'api#similar_business_centers'
    get 'api/page/:id' => 'api#page'

  post 'users/change_showed_city' => 'users#change_showed_city', as: 'change_showed_city'

  devise_for :users
  resources :cities
  resources :activities
  resources :notifications
  resources :lead_sources
  resources :room_types
  resources :leads
  resources :business_centers do
    collection {
      post :import
      get :parse_test
      get ':id/parse' => 'business_centers#parse', as: 'parse'
    }
  end
  resources :users
  resources :leads do
    collection do
      post :import
    end
  end
  resources :statuses
  resources :room_types

  get 'admin' => 'admin#index'
  get 'statistics' => 'admin#statistics'
  get 'zipal' => 'business_centers#zipal', as: 'zipal'
  get 'cian' => 'business_centers#cian', as: 'cian'
  get 'emls' => 'business_centers#emls', as: 'emls'
  get 'leads_select' => 'leads#select'

  root 'leads#index'

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]
  before_filter :authorize

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
    render :layout => !request.xhr?
  end

  # GET /statuses/1/edit
  def edit
    render :layout => !request.xhr?
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to :back, notice: 'Статус был успешно создан.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to :back, notice: 'Статус был успешно обновлен.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Статус был успешно удален.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params[:status].permit(:name, :color, :sort)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.slim
- if status.errors.any?
  - status.errors.full_messages.each do |message|
    .alert.alert-danger.alert-dismissable
      button.close[type="button" data-dismiss="alert" aria-hidden="true"]
      = message

= form_for(status, :html => {class: 'form-horizontal form-row-seperated'}) do |f|
  .portlet.light
    .portlet-title
      .caption
        span.caption-subject.font-green-sharp.bold.uppercase
        	= status.id ? "Сатус #{status.id}" : "Новый статус"

      = render partial: 'layouts/common/form/actions', :locals => {:model => status}
    .portlet-body
      .form-group
        label.col-md-2.control-label
          | Сортировка: 
        .col-md-10
          = f.number_field :sort, :class=>'form-control'
      .form-group
        label.col-md-2.control-label
          | Название: 
        .col-md-10
          = f.text_field :name, :class=>'form-control'
      .form-group
        label.col-md-2.control-label
          | Цвет: 
        .col-md-10.dropdown
          = f.hidden_field :color
          - if status.color
            span.picker_toggle data-toggle="dropdown" class=(status.color) data-id=(status.id ? status.id : 'new')
          - else
            span.picker_toggle data-toggle="dropdown" data-id=(status.id ? status.id : 'new') выбрать
          #colorPicker.dropdown-menu.theme-panel
            h3
              | ВЫБЕРИТЕ ЦВЕТ
            table
              tr
                td
                  ul.theme-colors
                    li.theme-color
                      span.theme-color-view.bg-blue
                    li.theme-color
                      span.theme-color-view.bg-blue-hoki
                    li.theme-color
                      span.theme-color-view.bg-blue-steel
                    li.theme-color
                      span.theme-color-view.bg-blue-madison
                    li.theme-color
                      span.theme-color-view.bg-blue-chambray
                    li.theme-color
                      span.theme-color-view.bg-blue-ebonyclay


                td
                  ul.theme-colors
                    li.theme-color
                      span.theme-color-view.bg-green
                    li.theme-color
                      span.theme-color-view.bg-green-meadow
                    li.theme-color
                      span.theme-color-view.bg-green-seagreen
                    li.theme-color
                      span.theme-color-view.bg-green-turquoise
                    li.theme-color
                      span.theme-color-view.bg-green-haze
                    li.theme-color
                      span.theme-color-view.bg-green-jungle
                td
                  ul.theme-colors
                    li.theme-color
                      span.theme-color-view.bg-red
                    li.theme-color
                      span.theme-color-view.bg-red-pink
                    li.theme-color
                      span.theme-color-view.bg-red-sunglo
                    li.theme-color
                      span.theme-color-view.bg-red-intense
                    li.theme-color
                      span.theme-color-view.bg-red-thunderbird
                    li.theme-color
                      span.theme-color-view.bg-red-flamingo
                td
                  ul.theme-colors
                    li.theme-color
                      span.theme-color-view.bg-yellow
                    li.theme-color
                      span.theme-color-view.bg-yellow-gold
                    li.theme-color
                      span.theme-color-view.bg-yellow-casablanca
                    li.theme-color
                      span.theme-color-view.bg-yellow-crusta
                    li.theme-color
                      span.theme-color-view.bg-yellow-lemon
                    li.theme-color
                      span.theme-color-view.bg-yellow-saffron
                td
                  ul.theme-colors
                    li.theme-color
                      span.theme-color-view.bg-purple
                    li.theme-color
                      span.theme-color-view.bg-purple-plum
                    li.theme-color
                      span.theme-color-view.bg-purple-medium
                    li.theme-color
                      span.theme-color-view.bg-purple-studio
                    li.theme-color
                      span.theme-color-view.bg-purple-wisteria
                    li.theme-color
                      span.theme-color-view.bg-purple-seance
                td
                  ul.theme-colors
                    li.theme-color
                      span.theme-color-view.bg-grey
                    li.theme-color
                      span.theme-color-view.bg-grey-cascade
                    li.theme-color
                      span.theme-color-view.bg-grey-silver
                    li.theme-color
                      span.theme-color-view.bg-grey-steel
                    li.theme-color
                      span.theme-color-view.bg-grey-cararra
                    li.theme-color
                      span.theme-color-view.bg-grey-gallery

app/views/statuses/_list.html.slim
.portlet.light
  .portlet-title
    .caption class=("caption-md" if params[:controller] == 'admin')
      i.fa.fa-th-list.font-green-sharp
      span.caption-subject.font-green-sharp.bold.uppercase Статусы
    - if params[:controller] == 'admin'
      .actions
        = link_to new_status_path, class: "btn btn-circle btn-icon-only btn-default", "data-target"=>"#modal", "data-toggle"=>"modal" do
          i.fa.fa-plus
  .portlet-body
    div class=("scroller" if params[:controller] == 'admin') style=("height: 305px;" if params[:controller] == 'admin') data-always-visible=1 data-rail-visible1=0 data-handle-color="#D7DCE2"
      .table-scrollable.table-scrollable-borderless
        table.table.table-hover.table-light#statuses_list
          thead
            tr.uppercase
              th
                | ID
              th
                | Сортировка
              th
                | Цвет
              th
                | Статус
          tbody
            - statuses.each do |status|
              tr
                td
                  = link_to status.id, edit_status_path(status), :class => 'primary-link', "data-target"=>"#modal", "data-toggle"=>("modal" if params[:controller] != 'users')
                td
                  = status.sort
                td.dropdown
                  - if status.color
                    span.picker_toggle data-toggle="dropdown" class=(status.color) data-id=(status.id)
                  - else
                    span.picker_toggle data-toggle="dropdown" data-id=(status.id ? status.id : 'new') нет
                td
                  = status.name

app/views/statuses/edit.html.slim
= render(partial: 'form', locals: { status: @status })

app/views/statuses/index.html.slim
= render partial: 'list', locals: { statuses: @statuses }

app/views/statuses/new.html.slim
= render(partial: 'form', locals: { status: @status })

app/views/statuses/show.html.slim
p#notice
  = notice
= link_to 'Edit', edit_status_path(@status)
|  | 
= link_to 'Back', statuses_path