config/routes.rb
Rails.application.routes.draw do

  resources :pages

  resources :services

    get 'api/business_centers'
    get 'api/cities'
    get 'api/regions'
    get 'api/metros'
    get 'api/room_types'
    get 'api/services'
    get 'api/business_center/:id' => 'api#business_center'
    get 'api/business_centers_for_map'
    get 'api/similar_business_centers/:id' => 'api#similar_business_centers'
    get 'api/page/:id' => 'api#page'

  post 'users/change_showed_city' => 'users#change_showed_city', as: 'change_showed_city'

  devise_for :users
  resources :cities
  resources :activities
  resources :notifications
  resources :lead_sources
  resources :room_types
  resources :leads
  resources :business_centers do
    collection {
      post :import
      get :parse_test
      get ':id/parse' => 'business_centers#parse', as: 'parse'
    }
  end
  resources :users
  resources :leads do
    collection do
      post :import
    end
  end
  resources :statuses
  resources :room_types

  get 'admin' => 'admin#index'
  get 'statistics' => 'admin#statistics'
  get 'zipal' => 'business_centers#zipal', as: 'zipal'
  get 'cian' => 'business_centers#cian', as: 'cian'
  get 'emls' => 'business_centers#emls', as: 'emls'
  get 'leads_select' => 'leads#select'

  root 'leads#index'

end

app/views/admin/_export.html.slim
.portlet.light
	.portlet-title.tabbable-line
		.caption.caption-md
			i.fa.fa-reply.font-green-sharp
			span.caption-subject.font-green-sharp.bold.uppercase
				| Экспорт

		ul.nav.nav-tabs
			li.active
				a href="#tab_export" data-toggle="tab"
					| Экспорт
			li
				a href="#tab_import" data-toggle="tab"
					| Импорт
	.portlet-body
		.tab-content
			.tab-pane.active id="tab_export"
				div class="scroller" style="height: 305px;" data-always-visible=1 data-rail-visible1=0 data-handle-color="#D7DCE2"
					ul.list-group
						li.list-group-item
							| Бизнес центры
							.pull-right.text-right
								= link_to "csv", business_centers_path(format: "csv"), class: "btn btn-xs grey-cascade"
								| &nbsp;
								= link_to "excel", business_centers_path(format: "xls"), class: "btn btn-xs grey-cascade"
						li.list-group-item
							| Клиенты
							.pull-right.text-right
								= link_to "csv", leads_path(format: "csv"), class: "btn btn-xs grey-cascade"
								| &nbsp;
								= link_to "excel", leads_path(format: "xls"), class: "btn btn-xs grey-cascade"
			.tab-pane id="tab_import"
				div class="scroller" style="height: 305px;" data-always-visible=1 data-rail-visible1=0 data-handle-color="#D7DCE2"
					ul.list-group
						li.list-group-item
							| Бизнес центры
							.pull-right.text-right
								= form_tag import_business_centers_path, multipart: true do
								  = file_field_tag(:file, {:requred => true, class: "hidden", onchange: "$(this).next().addClass('hidden').next().removeClass('hidden')"})
								  = link_to "выбрать", '#', onclick: "$(this).prev().click()", class: "btn btn-xs grey-cascade"
								  | &nbsp;
								  = submit_tag "импортировать", class: "btn btn-xs red hidden"
						li.list-group-item
							| Клиенты
							.pull-right.text-right
								= form_tag import_leads_path, multipart: true do
								  = file_field_tag(:file, {:requred => true, class: "hidden", onchange: "$(this).next().addClass('hidden').next().removeClass('hidden')"})
								  = link_to "выбрать", '#', onclick: "$(this).prev().click()", class: "btn btn-xs grey-cascade"
								  | &nbsp;
								  = submit_tag "импортировать", class: "btn btn-xs red hidden"

app/views/admin/_statistics_filter.html.slim
#fixed-filter
	.toggle.rotate
		i.fa.fa-filter.font-blue-hoki
		| &nbsp;
		span.caption-subject.bold.font-blue-hoki.uppercase Фильтр
	.portlet.light.bg-inverse.bordered
		.portlet-body
			= form_for_filterrific(@filterrific) do |f|
				.form-body
					.scroller style="height:70px"
						.form-group
							= f.label "Дата создания клиента:", class: "control-label"
							= f.text_field :with_created_at_between, class: 'form-control input-sm input-daterange'

					.text-right style="padding-top:8px"
						.pull-left
							= render_filterrific_spinner
						= link_to "Сбросить", reset_filterrific_url, class:"remove btn btn-sm default"
						| &nbsp;
						button.btn.btn-sm.blue-hoki type="submit" Применить

app/views/admin/index.html.slim
.row
	.col-md-6
		= render partial: 'users/list', locals: { users: User.all }
	.col-md-6
		= render partial: 'export'
.row
	.col-md-12
		= render partial: 'activities/list', locals: { activities: PublicActivity::Activity.order("created_at desc").limit(10) }
.row
	.col-md-6
		= render partial: 'cities/list', locals: { cities: City.all }
	.col-md-6
		= render partial: 'statuses/list', locals: { statuses: Status.all }
.row
	.col-md-6
		= render partial: 'lead_sources/list', locals: { lead_sources: LeadSource.all }
	.col-md-6
		= render partial: 'room_types/list', locals: { room_types: RoomType.all }
.row
	.col-md-6
		= render partial: 'services/list', locals: { services: Service.all }
	.col-md-6
		= render partial: 'pages/list', locals: { pages: Page.all }

app/views/admin/statistics.html.slim
= include_gon
= render partial: 'statistics_filter', locals: { filterrific: @filterrific }


.portlet.light
  .portlet-title
    .caption.caption-md
      i.fa.fa-bar-chart-o.font-green-sharp
      span.caption-subject.font-green-sharp.bold.uppercase Клиенты по месяцам
  .portlet-body
		#leads_by_day_legendPlaceholder
		#leads_by_day.chart

.portlet.light
  .portlet-title
    .caption.caption-md
      i.fa.fa-bar-chart-o.font-green-sharp
      span.caption-subject.font-green-sharp.bold.uppercase Клиенты по статусу
  .portlet-body
		#leads_by_status_legendPlaceholder
		#leads_by_status.chart

.portlet.light
  .portlet-title
    .caption.caption-md
      i.fa.fa-bar-chart-o.font-green-sharp
      span.caption-subject.font-green-sharp.bold.uppercase Источники клиентов по количеству
  .portlet-body
  	.row
  		.col-md-7.col-md-offset-1
				#lead_sources_by_clients style="height: 400px"
  		.col-md-4
  			.form-group.scroller style="height: 400px;" data-always-visible=1 data-rail-visible1=0 data-handle-color="#D7DCE2"
  				#lead_sources.checkbox-list
  					- @lead_sources_by_clients.each_with_index do |data, i|
  						label
  							= check_box_tag(:name, data[:label], i < 3)
  							= data[:label]
  							spab.badge.badge-success.pull-right
  								= data[:data]