config/routes.rb
Rails.application.routes.draw do

  resources :pages

  resources :services

    get 'api/business_centers'
    get 'api/cities'
    get 'api/regions'
    get 'api/metros'
    get 'api/room_types'
    get 'api/services'
    get 'api/business_center/:id' => 'api#business_center'
    get 'api/business_centers_for_map'
    get 'api/similar_business_centers/:id' => 'api#similar_business_centers'
    get 'api/page/:id' => 'api#page'

  post 'users/change_showed_city' => 'users#change_showed_city', as: 'change_showed_city'

  devise_for :users
  resources :cities
  resources :activities
  resources :notifications
  resources :lead_sources
  resources :room_types
  resources :leads
  resources :business_centers do
    collection {
      post :import
      get :parse_test
      get ':id/parse' => 'business_centers#parse', as: 'parse'
    }
  end
  resources :users
  resources :leads do
    collection do
      post :import
    end
  end
  resources :statuses
  resources :room_types

  get 'admin' => 'admin#index'
  get 'statistics' => 'admin#statistics'
  get 'zipal' => 'business_centers#zipal', as: 'zipal'
  get 'cian' => 'business_centers#cian', as: 'cian'
  get 'emls' => 'business_centers#emls', as: 'emls'
  get 'leads_select' => 'leads#select'

  root 'leads#index'

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :lead
  belongs_to :user
  belongs_to :creator, :class_name => 'User'

  default_scope { order('notify_at desc') }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  def index
    respond_to do |format|
      format.json do
        notifications = Notification
          .where('showed = ?', false)
          .where('user_id = ?', current_user.id)
          .where('notify_at <= ?', Time.now)
        json_notifications = notifications.to_json(:include => :lead)
        notifications.update_all(:showed => true)
        render json: json_notifications
      end
      format.html do
        notifications = Arel::Table.new(:notifications)
        cond = notifications[:user_id].eq(current_user.id)
        cond = cond.or(notifications[:creator_id].eq(current_user.id)) if current_user.is_admin
        @notifications = Notification.where(cond).page(params[:page])
      end
    end
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
    render :layout => !request.xhr?
  end

  # GET /notifications/1/edit
  def edit
    render :layout => !request.xhr?
  end

  # POST /notifications
  def create
    not_params = notification_params
    if current_user.is_admin && !params[:notification][:user_id].blank? then
      not_params[:user_id] = params[:notification][:user_id]
    else
      not_params[:user_id] = current_user.id
    end

    @notification = Notification.new(not_params)
    @notification.creator_id = current_user.id
    if @notification.save
      redirect_to params[:save_and_edit] ? edit_notification_path(@notification) : notifications_path, notice: 'Напоминание было успешно создано.'
    else
      render :new
    end
  end

  # PATCH/PUT /notifications/1
  def update
    not_params = notification_params
    if current_user.is_admin && !params[:notification][:user_id].blank? then
      not_params[:user_id] = params[:notification][:user_id]
    else
      not_params[:user_id] = current_user.id
    end
    not_params[:showed] = false if not_params[:notify_at] >= Time.now
    if @notification.update(not_params)
      redirect_to params[:save_and_edit] ? edit_notification_path(@notification) : notifications_path, notice: 'Напоминание было успешно обновлено.'
    else
      render :edit
    end
  end

  # DELETE /notifications/1
  def destroy
    if @notification.user_id == current_user.id || @notification.creator_id == current_user.id then
      @notification.destroy
      redirect_to notifications_url, notice: 'Напоминание было успешно удалено.'
    else
      redirect_to notifications_url, notice: 'Напоминание не может быть удалено вами.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def notification_params
      params.require(:notification).permit(:notify_at, :text, :lead_id, :creator_id)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.slim
- if notification.errors.any?
  - notification.errors.full_messages.each do |message|
    .alert.alert-danger.alert-dismissable
      button.close[type="button" data-dismiss="alert" aria-hidden="true"]
      = message

= form_for(notification, :html => {class: 'form-horizontal form-row-seperated'}) do |f|
  .portlet.light
    .portlet-title
      .caption
        i.fa.fa-group.font-green-sharp
        span.caption-subject.font-green-sharp.bold.uppercase
          = "Напоминание #{notification.id}" || "Новое напоминание"
      = render partial: 'layouts/common/form/actions', :locals => {:model => notification}
    .portlet-body
      .form-group
        = f.label :notify_at, class: "col-md-2 control-label"
        .col-md-4
          .input-group.date.form_datetime
            = f.text_field :notify_at, :value => notification.notify_at ? l(notification.notify_at, :format => '%d %B %Y - %H:%M') : nil, :class=>'form-control', :readonly => "readonly", size:"16"
            span.input-group-btn
              button.btn.default.date-set type="button"
                i.fa.fa-calendar

      .form-group
        = f.label :text, class: "col-md-2 control-label"
        .col-md-10
          = f.text_area :text, :class=>'form-control'

      .form-group
        = f.label :lead_id, class: "col-md-2 control-label"
        .col-md-10
          = f.text_field :lead_id, {:class=>'form-control', "data-ajax--url" => "/leads_select", "data-ajax--cache" => "true"}

      - if current_user.is_admin
        .form-group
          = f.label :user_id, class: "col-md-2 control-label"
          .col-md-10
            = f.collection_select :user_id, User.where('id != ?', current_user.id), :id, :first_name, {:include_blank => "Я"}, {:class => 'form-control input-medium'}

app/views/notifications/_list.html.slim
.table-scrollable
  table#notifications_list.table.table-hover.table-bordered
    thead
      tr
        th ID
        th Время
        th Текст
        th Клиент
        th Создатель
        - if current_user.is_admin
          th Исполнитель
    tbody
      - @notifications.each do |notification|
        tr
          td = link_to notification.id, edit_notification_path(notification), "data-target"=>"#modal", "data-toggle"=>"modal"
          td = time_tag notification.notify_at, {:format=>'%d %B %Y, %H:%M', class: 'text-muted'}
          td = notification.text
          td = link_to notification.lead.title, edit_lead_url(notification.lead), "data-target"=>"#modal", "data-toggle"=>"modal" if notification.lead
          td = (notification.creator.id != current_user.id ? notification.creator.first_name : 'Я') if notification.creator
          - if current_user.is_admin
            td = notification.user ? notification.user.first_name : 'Я'

= paginate @notifications if not @notifications.empty?

app/views/notifications/edit.html.slim
= render(partial: 'form', locals: { notification: @notification })

app/views/notifications/index.html.slim
.portlet.light
  .portlet-body
    .table-toolbar
      .btn-group
        = link_to new_notification_path, :class => "btn btn-sm green", "data-target"=>"#modal", "data-toggle"=>"modal" do
          | Создать 
          i.fa.fa-plus
    = render partial: 'list', locals: { notifications: @notifications }

app/views/notifications/new.html.slim
= render(partial: 'form', locals: { notification: @notification })

app/views/notifications/show.html.slim
p#notice = notice

p
  strong Notify at:
  = @notification.notify_at
p
  strong Text:
  = @notification.text
p
  strong Lead:
  = @notification.lead
p
  strong User:
  = @notification.user
p
  strong Creator:
  = @notification.creator_id

= link_to 'Edit', edit_notification_path(@notification)
'|
= link_to 'Back', notifications_path